### ISSUE TITLE
crash with sevtech ages latest version.

### ISSUE THREAD

**Issue by dodgythoughts** [LatvianModder/FTBUtilities#780]
Adding FTBUtilites/FTBLib to Sevtech ages server v3.0.8 causes a crash (oldest log attached)

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBLib (ftblib)
Caused by: java.lang.NoClassDefFoundError: com/feed_the_beast/ftblib/events/PermissionRegistryEvent

used to work fine with sevtech 3.0.7

the other two logs are different errors, from me changing the default settings in ftblibs config from true to false.

changing :autocreate_mp=true
replace_reload_command=false

[crash-2018-06-11_09.57.38-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2095758/crash-2018-06-11_09.57.38-server.txt)
[crash-2018-06-13_08.07.21-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2095759/crash-2018-06-13_08.07.21-server.txt)
[crash-2018-06-13_08.24.29-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2095760/crash-2018-06-13_08.24.29-server.txt)

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/770
